title: thunderrrcunt GitHub Pages
author: thunderrrcunt
email: jen@thunderrrcunt.com

description: A personal blog, highlighting my journey thru learning to code.



twitter_username: thunderrrcunt
github_username: thunderrrcunt

show_excerpts: true

theme: jekyll-theme-cayman
